### ISSUE TITLE
wheels for python 3.10 (and newer)

### ISSUE THREAD

**Issue by ikatechis** [patmjen/gorpho#1]
Hi @patmjen 

Thank you for this amazing little library!

Is it possible to create wheels for python 3.10 (and other newer versions) on pypi server?

**Comment by patmjen** [comment]
Yes, I will try to get on it later this week or next week.

**Comment by patmjen** [comment]
Should be available now - see here: https://github.com/patmjen/pygorpho/issues/3#issuecomment-2090235420
Due to issues with the build system on Windows, this took a while to find time for sadly.
